### ISSUE TITLE
Blue Robotics' low light hd usb camera keeps restarting

### ISSUE THREAD

**Issue by Williangalvani** [patrickelectric/mavlink-camera-manager#6]
The stream keeps on restarting, and we only get a few frames at a time. 
It seems to be caused by https://github.com/patrickelectric/mavlink-camera-manager/commit/b31c6fb33b8f4b18c2bafd0e444e72da8a2f768c.
t3.0.1 works fine.

**Comment by patrickelectric** [comment]
The fun fact is how we did not get this issue early 🤔

**Comment by Williangalvani** [comment]
I missed that change, I saw the problem multiple times and assumed it was a networking issue. Then I spent hours troubleshooting my networking until someone else reported the same issue and I connected the dots.

**Comment by patrickelectric** [comment]
Fixed in master with b8ee3127cee3bf6af60e2f79c93c27be956be626
